"""initial

Revision ID: d720c2d3fae2
Revises: 
Create Date: 2026-05-30 15:43:03.520545

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd720c2d3fae2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventories',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('submode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('collector_version', sa.String(length=40), nullable=True),
    sa.Column('script_sha256', sa.String(length=64), nullable=True),
    sa.Column('integrity_seed', sa.String(length=64), nullable=True),
    sa.Column('integrity_status', sa.String(length=32), nullable=True),
    sa.Column('integrity_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('redfish_probe_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('tls', sa.String(length=16), nullable=False),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('redfish_probe_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redfish_probe_history_ts'), ['ts'], unique=False)

    op.create_table('telemetry_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=40), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telemetry_events_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_events_ts'), ['ts'], unique=False)

    op.create_table('user_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('collection_jobs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('inventory_id', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('total_hosts', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('log_path', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_jobs_inventory_id'), ['inventory_id'], unique=True)

    op.create_table('log_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inventory_id', sa.String(length=40), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('host', sa.String(length=80), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_entries_inventory_id'), ['inventory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_entries_ts'), ['ts'], unique=False)

    op.create_table('servers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('inventory_id', sa.String(length=40), nullable=False),
    sa.Column('ilo_ip', sa.String(length=64), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=64), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('manufacturer', sa.String(length=80), nullable=True),
    sa.Column('form_factor', sa.String(length=80), nullable=True),
    sa.Column('generation', sa.String(length=32), nullable=True),
    sa.Column('ilo_generation', sa.String(length=16), nullable=True),
    sa.Column('ilo_firmware', sa.String(length=40), nullable=True),
    sa.Column('bios_version', sa.String(length=64), nullable=True),
    sa.Column('power_state', sa.String(length=16), nullable=True),
    sa.Column('health', sa.String(length=16), nullable=True),
    sa.Column('total_memory_gb', sa.Float(), nullable=True),
    sa.Column('total_storage_gb', sa.Float(), nullable=True),
    sa.Column('collection_status', sa.String(length=16), nullable=False),
    sa.Column('collection_error', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_id', 'serial_number', name='uq_inv_sn')
    )
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servers_inventory_id'), ['inventory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_servers_serial_number'), ['serial_number'], unique=False)

    op.create_table('components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.String(length=40), nullable=False),
    sa.Column('group', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('part_number', sa.String(length=64), nullable=True),
    sa.Column('serial_number', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('manufacturer', sa.String(length=80), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('capacity_value', sa.Float(), nullable=True),
    sa.Column('capacity_unit', sa.String(length=16), nullable=True),
    sa.Column('firmware_version', sa.String(length=40), nullable=True),
    sa.Column('health', sa.String(length=16), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_components_group'), ['group'], unique=False)
        batch_op.create_index(batch_op.f('ix_components_part_number'), ['part_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_components_server_id'), ['server_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_components_server_id'))
        batch_op.drop_index(batch_op.f('ix_components_part_number'))
        batch_op.drop_index(batch_op.f('ix_components_group'))

    op.drop_table('components')
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servers_serial_number'))
        batch_op.drop_index(batch_op.f('ix_servers_inventory_id'))

    op.drop_table('servers')
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_entries_ts'))
        batch_op.drop_index(batch_op.f('ix_log_entries_inventory_id'))

    op.drop_table('log_entries')
    with op.batch_alter_table('collection_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_jobs_inventory_id'))

    op.drop_table('collection_jobs')
    op.drop_table('user_settings')
    with op.batch_alter_table('telemetry_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telemetry_events_ts'))
        batch_op.drop_index(batch_op.f('ix_telemetry_events_kind'))

    op.drop_table('telemetry_events')
    with op.batch_alter_table('redfish_probe_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redfish_probe_history_ts'))

    op.drop_table('redfish_probe_history')
    op.drop_table('inventories')
    # ### end Alembic commands ###
