"""partsurfer cache

Revision ID: 326d0ea32da7
Revises: d720c2d3fae2
Create Date: 2026-06-04 00:00:14.140683

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '326d0ea32da7'
down_revision: Union[str, None] = 'd720c2d3fae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partsurfer_cache',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('partsurfer_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partsurfer_cache_fetched_at'), ['fetched_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partsurfer_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partsurfer_cache_fetched_at'))

    op.drop_table('partsurfer_cache')
    # ### end Alembic commands ###
